# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Helen Whitehead: Data Analytics Portfolio"
description: "A place to share some examples of my work"
author:      "Helen Whitehead"
